### ISSUE TITLE
Release supporting Go 1.9

### ISSUE THREAD

**Issue by ChrisHines** [haya14busa/reviewdog#117]
When do you plan to ship a release that supports Go 1.9? It looks like the change has already been made in https://github.com/haya14busa/reviewdog/commit/5ead4244a0603d30287b1b2cc040f52b19f032ce.

**Comment by JensRantil** [comment]
Why is it important to use Go 1.9?

**Comment by haya14busa** [comment]
v0.9.9 is released and it uses Go 1.10.x :tada: https://github.com/haya14busa/reviewdog/releases/tag/0.9.9
