### ISSUE TITLE
Make reviewdog a Github checker

### ISSUE THREAD

**Issue by JensRantil** [haya14busa/reviewdog#122]
See https://help.github.com/articles/about-status-checks/#checks. This would might also fix https://github.com/haya14busa/reviewdog/issues/87.

**Comment by MrGossett** [comment]
Any thoughts on how to accomplish this without altering existing behavior? Perhaps the new behavior is opt-in via an ENV var?

**Comment by stapelberg** [comment]
Why not just add a new binary?

**Comment by haya14busa** [comment]
> Note: Checks are currently in public beta and are only available for use with GitHub Apps.

I plan to try check API but it's still only for GitHub Apps. So need to wait.
Currently i have no plan to create reviewdog GitHub Apps.

**Comment by haya14busa** [comment]
wait... it might be interesting to build reviewdog GitHub app...! I may take a look at it on weekends.

**Comment by JensRantil** [comment]
@haya14busa Just curious, any progress over the weekend?

**Comment by haya14busa** [comment]
See #126. So far, so good :) 

I already implemented basic functionality and looks good to create github apps ;)

**Comment by derekperkins** [comment]
This looks amazing!
![image](https://user-images.githubusercontent.com/3588778/40465130-62ae600a-5edc-11e8-8d6a-3f7c0a5fd077.png)

**Comment by haya14busa** [comment]
I released new version and it supports GitHub check feature :tada:
https://twitter.com/haya14busa/status/1003795992271917056

**Comment by JensRantil** [comment]
Awesome! Looking forward to try it!
