### ISSUE TITLE
Error retrieving token for reviewdog.app

### ISSUE THREAD

**Issue by derekperkins** [haya14busa/reviewdog#139]
I went to https://reviewdog.app/gh/{owner}/{repo} to get my token after setting up the GitHub integration and got this error. When I login at reviewdog.app, it shows that my account is successfully connected. Anything else I can try?

```
failed to get repo: &github.ErrorResponse{Response:(*http.Response)(0xc008515170), Message:"Resource not accessible by integration", Errors:[]github.Error(nil), Block:(*struct { Reason string "json:\"reason,omitempty\""; CreatedAt *github.Timestamp "json:\"created_at,omitempty\"" })(nil), DocumentationURL:"https://developer.github.com/v3/repos/#get"}
```

**Comment by derekperkins** [comment]
It worked just now on a public repo. The original repo I tried it with was a private repo. Will this only work for public repos?

**Comment by haya14busa** [comment]
Thank you for trying new feature quickly and the quick report.

Hmm... maybe permission setting is wrong?
Do you confirm you installed the private repository to reviewdog app? https://github.com/apps/reviewdog

**Comment by derekperkins** [comment]
Yes, the private repo is included in the app permissions.

![image](https://user-images.githubusercontent.com/3588778/40948679-feebf402-6826-11e8-8aa3-76840f9aa36e.png)

**Comment by haya14busa** [comment]
Oh, i got it. reviewdog github app didn't request "Repository contents" before, but to check the authenticated user have permission to access the repository, reviewdog.app use one GitHub API request to get repository permission status.

I updated permission request of reviewdog app. Can you try again? Maybe you need to ack the new changed permission.

**Comment by derekperkins** [comment]
I just updated the app with the new permissions, but it didn't change the response. Is it possible that the response is cached somewhere? Do I need to wait a little bit for the settings to propagate?

**Comment by haya14busa** [comment]
oh, sorry i misunderstood the required permission.
Need to request https://developer.github.com/v3/apps/permissions/#metadata-permissions.

I updated the permission again, so can you try it again?

**Comment by derekperkins** [comment]
That worked. Thanks! I'm excited to try it out!
