### ISSUE TITLE
Add support for GitLab

### ISSUE THREAD

**Issue by hauleth** [haya14busa/reviewdog#28]

**Comment by haya14busa** [comment]
can you give me a API reference equivalent to GitHub Pull Request API?
We need some API and needs comment API for pull-request at least

**Comment by hauleth** [comment]
https://docs.gitlab.com/ce/api/merge_requests.html#comments-on-merge-requests <https://docs.gitlab.com/ce/api/merge_requests.html#comments-on-merge-requests>
--

Łukasz Niemier
lukasz@niemier.pl

**Comment by haya14busa** [comment]
https://docs.gitlab.com/ce/api/notes.html#merge-requests

It seems it doesn't support inline comment like github?

**Comment by hauleth** [comment]
I believe you would need to comment each commit independently https://docs.gitlab.com/ce/api/commits.html#post-comment-to-commit <https://docs.gitlab.com/ce/api/commits.html#post-comment-to-commit>

There is similar project which handles it somehow https://github.com/mmozuras/pronto <https://github.com/mmozuras/pronto>
--

Łukasz Niemier
lukasz@niemier.pl

**Comment by haya14busa** [comment]
Thanks!  https://docs.gitlab.com/ce/api/commits.html#post-comment-to-commit  is the API I was looking for.

From a quick read, I guess I can create a repository on gitlab free for testing, so I think I can add gitlab support.

I'll try to implement in my spare time.

**Comment by hauleth** [comment]
@haya14busa any update?

**Comment by haya14busa** [comment]
not yet. Considering the number of upvotes, I guess I should make this issue hige priority. Thanks.

**Comment by hauleth** [comment]
@haya14busa ping. Sorry for that, but I am not proficient with Go enough to provide you any PR with such functionality.

**Comment by nakatanakatana** [comment]
@haya14busa 
I make PR. Please review it. 
https://github.com/haya14busa/reviewdog/pull/121

**Comment by haya14busa** [comment]
New reviewdog version with GitLab integration is released :tada:

https://github.com/haya14busa/reviewdog/releases/tag/0.9.10
https://twitter.com/haya14busa/status/1011037271909326848

Thanks again, @nakatanakatana and @masamotod for implementing GitLab integration :+1:
