### ISSUE TITLE
Add support for FxCop/Mono.Gendarme to review .Net code

### ISSUE THREAD

**Issue by Lafriks** [haya14busa/reviewdog#31]
Would be nice to have ability to give dogreview FxCop or Mono.Gendarme XML reports

**Comment by haya14busa** [comment]
can you give me some references?
I want to know the report format of FxCop or Mono.Gendarme XML reports.

**Comment by haya14busa** [comment]
I added checkstyle xml format https://github.com/haya14busa/reviewdog/tree/bb11307af494bd85a65afc2da3e3effd51fc0eae#checkstyle-format

I think you can write converter from  FxCop or Mono.Gendarme XML to checkstyle format.

**Comment by Lafriks** [comment]
Thanks, will check how this works out!
