### ISSUE TITLE
Cannot 'go get' due to some API changes in go-github

### ISSUE THREAD

**Issue by hkurokawa** [haya14busa/reviewdog#80]
I tried to install the command with `go get` but failed. It seems [go-github](https://github.com/google/go-github) changed some of the APIs (see https://github.com/google/go-github/pull/529).

```
$ go get -u github.com/haya14busa/reviewdog/cmd/reviewdog 
# github.com/haya14busa/reviewdog
./github.go:132: not enough arguments in call to g.cli.PullRequests.CreateReview
        have (string, string, int, *github.PullRequestReviewRequest)
        want ("context".Context, string, string, int, *github.PullRequestReviewRequest)
./github.go:151: not enough arguments in call to g.cli.PullRequests.CreateComment
        have (string, string, int, *github.PullRequestComment)
        want ("context".Context, string, string, int, *github.PullRequestComment)
./github.go:190: not enough arguments in call to g.cli.PullRequests.Get
        have (string, string, int)
        want ("context".Context, string, string, int)
./github.go:208: not enough arguments in call to g.cli.PullRequests.ListComments
        have (string, string, int, nil)
        want ("context".Context, string, string, int, *github.PullRequestListCommentsOptions)
```

**Comment by hkurokawa** [comment]
My apologies. I've just realised you are using golang/dep. So probably the better solution is to update README instead of catching up with the latest go-github.

Anyway, I am keeping the issue open as someone might have the same issue in future. Feel free to close the issue if you think it is not a problem.

Thanks.

**Comment by haya14busa** [comment]
no problem. I'm considering to catch up go-github soon (your p-r #81 may help).

> So probably the better solution is to update README instead of catching up with the latest go-github.

If you run `go get` to install reviewdog, the better solution is not using 'go get'. Instead, use released binary.

**Comment by hkurokawa** [comment]
Thank you for your response. And I agree with that downloading the released binary is a better way to access the build output. On the other hand, for those who want to contribute to the repo like me, it would be great if there is an instruction about how to setup development environment.

Honestly, I am not familiar with go vendoring system. So it might be only me who do not know how to build this repository.

Anyway, thank you for your clarification. Feel free to close this issue. Thanks!
