### ISSUE TITLE
Add documentation for Jenkins

### ISSUE THREAD

**Issue by Marimoiro** [haya14busa/reviewdog#89]
こちらのツールをJenkins上で利用させていただきました。
ありがとうございます。

一点はまった部分があるのでREADMEに追記しておいていただけると嬉しいなと思います。

jenkinsでGitHub pull request builder pluginを使用したときにCI_COMMITを以下の値にすると失敗します。

export CI_COMMIT=$(git rev-parse HEAD)

[{Resource:PullRequestReviewComment Field:commit_id Code:custom Message:commit_id is not part of the pull request}]

これは仮にマージされたコミットでAPIをたたいているからだと思います。
以下のようにすると正しく成功します。

export CI_COMMIT=${ghprbActualCommit}

**Comment by haya14busa** [comment]
ありがとうございます！いま個人的に触れるJenkins もってないんですが，コメントを英語になおして書けばよいでしょうか...?

もしよければ `CI_COMMIT` だけでなく GitHub pull request builder plugin を使ってどうやって動かせばいいかの手順もいただけると大変うれしいです．英語だと嬉しいですが，日本語でも勿論okです．

**Comment by Marimoiro** [comment]
すいません。
英語は自信ないのでお願いします…

僕の環境では以下の通りで動きました。

1. ビルドトリガーにGitHub Pull Request Builderを設定する
2. gitの設定を以下の通りにする
・sha1は自動設定される環境変数
![repository](https://cloud.githubusercontent.com/assets/5342721/24338926/f6b6933a-12e3-11e7-8de4-260225a2b4bf.png)

3. シェルの実行

export CI_PULL_REQUEST=${ghprbPullId}
export CI_REPO_OWNER=haya14busa
export CI_REPO_NAME=reviewdog
export CI_COMMIT=${ghprbActualCommit}
export REVIEWDOG_INSECURE_SKIP_VERIFY=true

export REVIEWDOG_GITHUB_API_TOKEN="<your token>"

**Comment by haya14busa** [comment]
ありがとうございます！

**Comment by Marimoiro** [comment]
反映ありがとうございます！

**Comment by haya14busa** [comment]
こちらこそありがとうございましたっ :+1:
