### ISSUE TITLE
Support Pull Request Reviews for GitHub Enterprise

### ISSUE THREAD

**Issue by jcbwlkr** [haya14busa/reviewdog#96]
Hello, haya14busa! Thanks for this great tool!

I can see in the code that reviewdog knows how to post comments in one big review but the behavior is disabled for Enterprise users. From what I can tell the Enterprise API now supports reviews. Can we get that feature enabled?

**Comment by haya14busa** [comment]
Do you know how to check the review API is available or version of GHE?

Or, maybe we can totally disable old way to post comments?
Do you know when did the review API become available and GHE policy or something about updating version?

**Comment by jcbwlkr** [comment]
It looks to me that the review api became available in GHE v2.9. I can't tell if there is a way in the API to check your version. One option might be to do a `GET` against the reviews endpoint for a known PR and see if it 404s.
